FROM docker.io/redhat/ubi9-minimal:latest

LABEL maintainer="pvn@novarese.net"
LABEL name="2023-12-demo-baseline"
LABEL org.opencontainers.image.title="2023-12-demo-baseline"
LABEL org.opencontainers.image.description="Simple image to test various policy rules with Anchore Enterprise."

HEALTHCHECK --timeout=10s CMD /bin/true || exit 1

COPY log4j-core-2.14.1.jar /

RUN set -ex && \
    microdnf -y install python3 python3-pip nodejs shadow-utils && \
    pip3 install --index-url https://pypi.org/simple --no-cache-dir aiohttp==3.7.3 pytest==7.0.1 urllib3==1.26.10 botocore==1.26.9 six==1.15.0 numpy==1.19.4 && \
    npm install -g --cache /tmp/empty-cache xmldom@0.4.0 && \
    npm cache clean --force && \
    microdnf -y clean all && \
    rm -rf /var/cache/yum /tmp 

## just to make sure we have a unique build each time
RUN date > /image_build_timestamp && \
    touch image_build_timestamp_$(date +%Y-%m-%d_%T)
    
USER nobody
ENTRYPOINT /bin/false
